---
classoption: portrait
geometry: left=2cm,right=2cm,top=3cm,bottom=3cm
header-includes:
        \usepackage{vntex}
        \usepackage{longtable}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhead[C]{BẢNG KÊ DỊCH VỤ TÌM KIẾM KHÁCH HÀNG}
        \fancyhead[R]{Số VPB-2023-07}
output:
  pdf_document: default 
  word_document: 
  html_document:
  df_print: paged
mainfont: Times New Roman
---
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE, r,echo=FALSE}
options(scipen=99)
library(dplyr)
library(readxl)
library(data.table)
library(dplyr)
library(magrittr)
library(knitr)
library(kableExtra)
library(pander)
library(stringr)
library(janitor)
rm(list=ls())
###!!!! always need to change

report_mon <- format(Sys.Date()-30,'%Y-%m')
mon = paste0(substr(report_mon,6,7),"-",substr(report_mon,1,4))

#local_path = '/home/baokhanh/vpb/'
#path = paste0(local_path,report_mon)
#file_recon <- paste0(path,"/vpb_converted_",report_mon,"_recon_cycle.xlsx")

upl_hq <- read.csv('/home/linhnguyen/04.Reconcile/04.VPBank/vpb_converted_cycle_report_upl.csv') %>% 
  select(-product_type,-receiver,-national_id,-phone_number,-customer_name) %>% 
  rename(fee_w_vat=new_price_vat,fee_no_vat= new_price_exc_vat  ) %>% 
  data.table()
upl_hq$lead_id = as.character(upl_hq$lead_id)
upl_hq$disbursed_date <- strftime(upl_hq$disbursed_date,format = '%d-%m-%Y')
```
\begin{flushleft}\fontsize{13pt}{14pt}\selectfont
  \rmfamily\textbf{CHI TIẾT GIẢI NGÂN UPL HQ}
\end{flushleft}
```{r echo=FALSE, warning=FALSE}
if (nrow(upl_hq)>0){
  kable(upl_hq %>% adorn_totals() %>% 
        #set_colnames(c("Loại SP","Đầu mối","Converted","Phí dịch vụ chưa VAT","Phí dịch vụ có VAT")) %>% 
        data.table(), 
      "latex", booktabs = T,format.args = list(big.mark = ".",decimal.mark=","),align='l',longtable = TRUE,row.names = TRUE) %>% 
  kable_styling(latex_options = c("hold_position", "repeat_header"),font_size = 5, full_width =F,row_label_position = "c") %>% 
  row_spec(0,bold = T) %>% 
  row_spec(nrow(upl_hq)+1,bold = T)
}
```

```{r include=FALSE}
rm(list=ls())
```